name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0

      - name: Build
        run: dotnet build

      - name: Run unit tests
        run: dotnet test -v n

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install integration test dependencies
        run: |
          pip install pandas
          npm install --global pyright

      - name: Run integration tests
        run: python integration_tests.py
        working-directory: integration
        env:
          NO_DEBUG: true
