name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Build
        run: dotnet build

      - run: echo ${{github.ref}}
      - run: echo ${{github.event_name}}

      - name: Clone Lean
        run: git clone https://github.com/QuantConnect/Lean.git lean
        if: github.ref == 'refs/head/master' && github.event_name == 'push'

      - name: Run
        run: dotnet run --project LeanPythonGenerator lean lean-types
        if: github.ref == 'refs/head/master' && github.event_name == 'push'

      - name: List types directory
        run: ls lean-types
        if: github.ref == 'refs/head/master' && github.event_name == 'push'
