name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Build
        run: dotnet build

      - name: Stop build
        uses: andymckay/cancel-action@0.2
        if: ${{ github.ref != 'ref/head/master' }}

      - name: Clone Lean
        run: git clone https://github.com/QuantConnect/Lean.git lean

      - name: Run
        run: dotnet run --project LeanPythonGenerator lean lean-types

      - name: List types directory
        run: ls lean-types
